完成举报功能模块
HFUT-Newx/hfut-studyroom pull request #2
Opened 2021-12-18 11:09 UTC by SnowingFox

已完成举报功能模块

2021-12-18 13:03 UTC, fzxiao233 requested changes
这个pr有以下几点问题：
- 不要更改原代码的格式化风格，甚至提交.prettierrrc
- 不要提交.idea目录
- 代码多出出现了重复的import标记，请找出并合并
- 代码引入了无效的scss文件

2021-12-18 13:26 UTC, SnowingFox commented
@fzxiao233 
### 1. 关于风格的问题，我看您写的源码如
```jsx
<Picker range={timeList.map((d) => d.date)} onChange={(e) => handleDateChange(e)} value={date}>
```
这么长一串的代码横着阅读不是很清晰，推荐改成
```jsx
<Picker 
  range={timeList.map((d) => d.date)} 
  onChange={(e) => handleDateChange(e)} 
  value={date}
 />
```
- 另外项目记得要配上prettier的配置文件，这样后来者提PR的时候才能更好的符合原作者风格，您可以将您之前写好的prettier文件发给我，我好格式化一下风格
- 以及箭头函数一定要加上括号，无论是不是只有一个参数
### 2. `.idea`, 重复的`import`(IDE自动引入没有注意到)，无效的 `scss`文件的问题已修改

2021-12-18 13:32 UTC, fzxiao233 commented
请不要提交.idea目录！

2021-12-21 08:29 UTC, SnowingFox commented
A

2021-12-21 08:29 UTC, closed without merging